In [1]:
library(tidyr)
UN <- readRDS(url('https://github.com/omerfyalcin/colab-data/blob/main/UN.rds?raw=true'))

## Fitting a Linear Model

The `lm()` function is used to fit a multiple linear regression model.
Like in a simple linear regression, the function expects a formula argument.
Each additional predictor is added with a `+` sign to the right-hand side of the formula.

### UN Data

Let's use UN data from the *carData* package for demonstration, provided in the beginning of this notebook from GitHub for your convenience.
Use the `head()` function to visually inspect the first six rows of the data.

In [2]:
# Write your code here
head(UN)

               region    group  fertility ppgdp   lifeExpF pctUrban
Afghanistan    Asia      other  5.968       499.0 49.49     23
Albania        Europe    other  1.525      3677.2 80.40     53
Algeria        Africa    africa 2.142      4473.0 75.00     67
American Samoa NA        NA        NA          NA    NA     NA
Angola         Africa    africa 5.135      4321.9 53.17     59
Anguilla       Caribbean other  2.000     13750.1 81.10    100
               infantMortality
Afghanistan    124.53500
Albania         16.56100
Algeria         21.45800
American Samoa  11.29389
Angola          96.19100
Anguilla              NA

Now, use the `str()` function or `glimpse()` (from tidyr) to learn more.

In [3]:
# Write your code here
str(UN)

'data.frame':	213 obs. of  7 variables:
 $ region         : Factor w/ 8 levels "Africa","Asia",..: 2 4 1 NA 1 3 5 2 3 8 ...
 $ group          : Factor w/ 3 levels "oecd","other",..: 2 2 3 NA 3 2 2 2 2 1 ...
 $ fertility      : num  5.97 1.52 2.14 NA 5.13 ...
 $ ppgdp          : num  499 3677 4473 NA 4322 ...
 $ lifeExpF       : num  49.5 80.4 75 NA 53.2 ...
 $ pctUrban       : num  23 53 67 NA 59 100 93 64 47 89 ...
 $ infantMortality: num  124.5 16.6 21.5 11.3 96.2 ...

Finally, call the `summary()` function to get some descriptive statistics.

In [5]:
# Write your code here
summary(UN)

        region      group       fertility         ppgdp
 Africa    :53   oecd  : 31   Min.   :1.134   Min.   :   114.8
 Asia      :50   other :115   1st Qu.:1.754   1st Qu.:  1283.0
 Europe    :39   africa: 53   Median :2.262   Median :  4684.5
 Latin Amer:20   NA's  : 14   Mean   :2.761   Mean   : 13012.0
 Caribbean :17                3rd Qu.:3.545   3rd Qu.: 15520.5
 (Other)   :20                Max.   :6.925   Max.   :105095.4
 NA's      :14                NA's   :14      NA's   :14
    lifeExpF        pctUrban      infantMortality
 Min.   :48.11   Min.   : 11.00   Min.   :  1.916
 1st Qu.:65.66   1st Qu.: 39.00   1st Qu.:  7.019
 Median :75.89   Median : 59.00   Median : 19.007
 Mean   :72.29   Mean   : 57.93   Mean   : 29.440
 3rd Qu.:79.58   3rd Qu.: 75.00   3rd Qu.: 44.477
 Max.   :87.12   Max.   :100.00   Max.   :124.535
 NA's   :14      NA's   :14       NA's   :6

You can also check the relevant documentation page from CRAN to learn more: [https://rdrr.io/cran/carData/man/UN.html](https://rdrr.io/cran/carData/man/UN.html) (This is one of couple of websites that provide CRAN documentation with a more user friendly interface. If you loaded the `carData` package and called `?UN` you would see the same information).

### Linear Model

Now, let's fit a linear regression model with female life expectancy as the outcome variable and with GDP per capita and share of urban population as explanatory variables.

In [6]:
lm(lifeExpF ~ ppgdp + pctUrban, data = UN)

Call:
lm(formula = lifeExpF ~ ppgdp + pctUrban, data = UN)

Coefficients:
(Intercept)        ppgdp     pctUrban
  59.545981     0.000162     0.183656

While this output is helpful, it does not report some of the most important information, such as the standard errors.
To do that, we need the `summary()` function.

Let's run the same model, but call `summary()` on it:

In [7]:
summary(lm(lifeExpF ~ ppgdp + pctUrban, data = UN))

Call:
lm(formula = lifeExpF ~ ppgdp + pctUrban, data = UN)

Residuals:
    Min      1Q  Median      3Q     Max
-21.814  -4.303   1.938   5.525  15.898

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 5.955e+01  1.565e+00  38.050  < 2e-16 ***
ppgdp       1.620e-04  3.741e-05   4.330 2.37e-05 ***
pctUrban    1.837e-01  2.940e-02   6.246 2.56e-09 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 7.767 on 196 degrees of freedom
  (14 observations deleted due to missingness)
Multiple R-squared:  0.4173,	Adjusted R-squared:  0.4114
F-statistic: 70.19 on 2 and 196 DF,  p-value: < 2.2e-16

You have seen other variables in the UN dataset above.
Add another predictor of your choice to the right-hand side of the formula.
Did the coefficients change?

In [ ]:
# Wriite your code here

Run the following regression. Out of the four explanatory variables, which one has the smallest p-value? (the Intercept is the smallest but that's not an explanatory variable.)

Why do you think that variable has such a small p-value?

In [8]:
summary(lm(lifeExpF ~ ppgdp + pctUrban + infantMortality + fertility, data = UN))

Call:
lm(formula = lifeExpF ~ ppgdp + pctUrban + infantMortality +
    fertility, data = UN)

Residuals:
     Min       1Q   Median       3Q      Max
-19.3611  -1.0767   0.7094   1.7145   8.2569

Coefficients:
                  Estimate Std. Error t value Pr(>|t|)
(Intercept)      8.149e+01  1.237e+00  65.859  < 2e-16 ***
ppgdp            5.875e-05  1.878e-05   3.129  0.00204 **
pctUrban         4.552e-03  1.518e-02   0.300  0.76455
infantMortality -2.788e-01  1.827e-02 -15.260  < 2e-16 ***
fertility       -6.543e-01  3.693e-01  -1.772  0.07807 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.551 on 188 degrees of freedom
  (20 observations deleted due to missingness)
Multiple R-squared:  0.8809,	Adjusted R-squared:  0.8784
F-statistic: 347.6 on 4 and 188 DF,  p-value: < 2.2e-16

## Prediction and Inference

Linear regression models are typically used for two main purposes: prediction and inference.
Prediction is the main concern in the machine learning tradition: construct a model and apply it to new cases to get a predicted value for the outcome variable.
Social sciences are more concerned with explanation of mechanisms, causes and effects, and statistical significance and inference---usually through null hypothesis significance testing on one or more explanatory variables.

### Prediction with predict()

R has various functions that can be used for these purposes, and we'll just take a look at two here.

The `predict()` function can be used to make predictions using a linear regression model for new cases.

Fit the very first model again (with female life expectancy as the outcome variable and with GDP per capita and share of urban population as explanatory variables), but assign the output to an object called `fit`. (Assign the output from `lm()` to `fit`, **not** the output from `summary(lm(...))`.)

In [9]:
# Write your code here
fit = lm(lifeExpF ~ ppgdp + pctUrban, data = UN)

If you simply use the `fit` object as the only input to the `predict()` function, it will produce the predicted female life expectancy for the observations in the model (which are also used to calculate residuals).
Let's try it out:

In [10]:
head(predict(fit), n = 10)

Afghanistan     Albania     Algeria      Angola    Anguilla   Argentina
   63.85091    69.87549    72.57560    71.08187    80.13925    78.11034
    Armenia       Aruba   Australia     Austria
   71.79096    71.88003    85.14531    79.35085

Importantly, `predict()` can be used to make predictions about new data points that we supply.
Let's create one that we can then use:

In [11]:
set.seed(3)

df <- data.frame(ppgdp = sample(UN$ppgdp, size = 10, replace = T),
           pctUrban = sample(UN$pctUrban, size = 10, replace = T))

df

   ppgdp   pctUrban
1   4321.9 56
2    816.0 75
3   1239.8 68
4    450.8 57
5    816.0 28
6    218.6 68
7  35319.5 96
8    741.1 78
9  26503.8 59
10 48906.2 63

We used `sample()` to sample from the existing values.
This will ensure that we have plausible input values that are not out of the range that was used when fitting the model.
But we will have many combinations of the input variables that the model did not use.

Now, use `df`, as the second argument to the `predict()` function to get predictions (while still using `fit` as the first argument.)

In [12]:
# Write your code here
predictions <- predict(fit, newdata = df)
head(predictions, n = 10)

       1        2        3        4        5        6        7        8
70.53091 73.45237 72.23544 70.08740 64.82055 72.06999 82.89913 73.99120
       9       10
74.67561 79.03970


### Statistical Inference

The main tool of statistical inference for a linear model is something we have already seen: the `summary()` function.
It reports the standard error, t value, p value for each coefficient and even marks each coefficient for different levels of significance.
It also reports an F-statistic and a p-value associated with that, which can be used to assess the explanatory power of the predictors altogether.

Let's revisit `summary()`. Call the `summary()` function on the `fit` object.

In [13]:
# Write your code here
summary(fit)

Call:
lm(formula = lifeExpF ~ ppgdp + pctUrban, data = UN)

Residuals:
    Min      1Q  Median      3Q     Max
-21.814  -4.303   1.938   5.525  15.898

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 5.955e+01  1.565e+00  38.050  < 2e-16 ***
ppgdp       1.620e-04  3.741e-05   4.330 2.37e-05 ***
pctUrban    1.837e-01  2.940e-02   6.246 2.56e-09 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 7.767 on 196 degrees of freedom
  (14 observations deleted due to missingness)
Multiple R-squared:  0.4173,	Adjusted R-squared:  0.4114
F-statistic: 70.19 on 2 and 196 DF,  p-value: < 2.2e-16

The results show p-values that are very small, providing strong evidence against the null hypothesis that the real "population" partial coefficients for `ppgdp` and `pctUrban` are zero.
We have reason to believe that these coefficients are not zero (i.e. to believe in the alternative hypothesis).
The three stars (***) indicate statistical significance at the 0.01 level.

However, as we have previously seen, looking at confidence intervals reveals much more information than the hypothesis test alone.
For example, it would show us what the range of plausible values for these variables are.
Right now, we believe they are not zero, but we are not sure about how close to or far from zero they can plausibly be.

We can use the `confint()` function to construct the relevant confidence intervals.
Let's construct a confidence interval for the GDP per capita variable's coefficient.

In [14]:
confint(fit, 'ppgdp')

      2.5 %        97.5 %
ppgdp 8.822666e-05 0.0002357978

The `confint()` function constructs a 95% confidence interval by default. But that can be changed:

In [15]:
confint(fit, 'ppgdp', level = 0.99)

      0.5 %        99.5 %
ppgdp 6.469313e-05 0.0002593313

Now, construct a confidence interval for the `pctUrban` variable at the 90% level: